-- DROP TABLE IF EXISTS dispatch_group;
-- DROP TABLE IF EXISTS dispatch_task;
-- DROP TABLE IF EXISTS dispatch_taskway;
-- DROP TABLE IF EXISTS dispatch_taskparam;
-- DROP TABLE IF EXISTS dispatch_tasklog;
-- DROP TABLE IF EXISTS dispatch_tasktime;
-- DROP TABLE IF EXISTS dispatch_taskuser;
-- DROP TABLE IF EXISTS dispatch_task_recallparam;
-- DROP TABLE IF EXISTS dispatch_taskwayclass;
-- DROP TABLE IF EXISTS ref_refinfo;

-- DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
-- DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;
-- DROP TABLE IF EXISTS QRTZ_LOCKS;
-- DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_JOB_DETAILS;
-- DROP TABLE IF EXISTS QRTZ_CALENDARS;

CREATE TABLE ref_refinfo (
  pk_ref varchar(200) NOT NULL,
  refname varchar(300) DEFAULT NULL,
  refcode varchar(300) DEFAULT NULL,
  refclass varchar(300) DEFAULT NULL,
  refurl varchar(300) DEFAULT NULL,
  md_entitypk varchar(300) DEFAULT NULL,
  productType varchar(300) DEFAULT NULL,
  PRIMARY KEY (pk_ref)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 参照类型
INSERT INTO ref_refinfo (pk_ref, refname, refcode, refclass, refurl, md_entitypk, productType) VALUES ('001', '调度任务规则', 'dispatch', 'none', '/iuap-saas-dispatch-service/taskwayref/', 'dispatch', 'ref');

CREATE TABLE dispatch_group(
     id VARCHAR(40) NOT NULL,
	 sysid VARCHAR(40),/* 应用id*/
	 tenantid VARCHAR(40),/* 租户id*/
	 name VARCHAR(200) NOT NULL,/*分组名称*/
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE dispatch_task(
     id VARCHAR(40) NOT NULL,
	 sysid VARCHAR(40),/* 应用id*/
	 tenantid VARCHAR(40),/* 租户id*/
	 code VARCHAR(200) NOT NULL,/*任务编码*/
	 name VARCHAR(200) NOT NULL,/*任务名称*/
     groupid VARCHAR(40),  /*对应分组id*/
     cronexpression VARCHAR(200),/*定时规则表达式*/
     taskwayid VARCHAR(40),/*调用方式ID*/
     description VARCHAR(250), /*描述信息*/
     flag int(1) DEFAULT '1',/*1启动，0暂停*/
     createtime TIMESTAMP,/*任务创建时间*/
     userid VARCHAR(64),  /*创建人ID*/
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE dispatch_tasktime(
     id VARCHAR(40) NOT NULL,
	 starttime TIMESTAMP,/* 开始时间*/
	 endtime TIMESTAMP,/* 结束时间*/
	 modetype int(1) DEFAULT '0',/*天0/周1/月2*/
	 modefrequency int(2) DEFAULT '1', /*每隔【value】多久(单位是天，周，月)*/
	 modevaule VARCHAR(40), /*周1-7/月1-31,0*/
	 duramode int(1) DEFAULT '0',/*一次0/1周期*/
	 duravalue VARCHAR(200),/*一次值或者周期值*/
	 periodmode int(1) DEFAULT '0',/*0小时/1分钟*/
	 periodstart VARCHAR(40),/*一天中的开始时间段，时：分*/
	 periodend VARCHAR(40),/*一天中的结束时间段，时：分*/
	 taskid VARCHAR(40),/*任务的id*/
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE dispatch_taskuser(
     id VARCHAR(40) NOT NULL,
	 ucode VARCHAR(200),/* 用户编码*/
	 uname VARCHAR(200),/* 用户名称*/
	 msg int(1) DEFAULT '0',/*消息中心接收推送*/
	 email int(1) DEFAULT '0', /*email接收推送*/
	 phone int(1) DEFAULT '0', /*电话接收推送*/
	 taskid VARCHAR(40), /*对应的任务id*/
	 userid VARCHAR(64), /*对应的用户id*/
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE dispatch_taskway(
     id VARCHAR(40) NOT NULL,
     code VARCHAR(200),/* 编码*/
     name VARCHAR(200),/* 名称*/
	 url VARCHAR(200),/* http的url或者class名称*/
	 classname VARCHAR(200),
        taskwayclassid VARCHAR(40),
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into DISPATCH_TASKWAY (ID, CODE, NAME, URL, CLASSNAME, TASKWAYCLASSID) values ('001', 'rule01', 'rule01', 'http://localhost:8080/iuap-saas-dispatch-service/taskReturnExample/success', null, '001');
insert into DISPATCH_TASKWAY (ID, CODE, NAME, URL, CLASSNAME, TASKWAYCLASSID) values ('002002', '002', '002', 'http://localhost:8080', null, '001');


CREATE TABLE dispatch_taskwayclass(
     id VARCHAR(40) NOT NULL,
	 sysid VARCHAR(40),
	 tenantid VARCHAR(40),
	 code VARCHAR(200) NOT NULL,
	 name VARCHAR(200) NOT NULL,
	 parentid VARCHAR(40),
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into DISPATCH_TASKWAYCLASS (ID, SYSID, TENANTID, CODE, NAME, PARENTID) values ('001', null, null, 'testClass01', 'testClass01', null);

CREATE TABLE dispatch_taskparam(
     id VARCHAR(40) NOT NULL,
	 code VARCHAR(200),/* 名称*/
	 name VARCHAR(200),/* 参数名称*/
	 paramvalue VARCHAR(200),/* 参数取值*/
	 taskwayid VARCHAR(40),
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE dispatch_task_recallparam(
     id VARCHAR(40) NOT NULL,
     taskwayid VARCHAR(40) NOT NULL,/*规则主键*/
     taskparamid VARCHAR(40) NOT NULL,/*规则参数主键*/
     taskid VARCHAR(40) NOT NULL,/*任务主键*/
	 paramvalue VARCHAR(200), /*回调参数值*/
	 PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE dispatch_tasklog(
     id VARCHAR(40) NOT NULL,
	 starttime TIMESTAMP,/* 开始时间*/
	 endtime TIMESTAMP,/* 结束时间*/
	 visible int(1) DEFAULT '1',/*0不显示，1显示*/
	 flag int(1) DEFAULT '0',/*0失败，1成功*/
     content blob,  /*对应异常日志的内容*/
     taskid VARCHAR(40),/*对应任务的id*/
     jobcode VARCHAR(64),/*非界面添加的任务code*/
     jobgroupcode VARCHAR(64),/*非界面添加的任务分组code*/
     PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE QRTZ_JOB_DETAILS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME  VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    JOB_CLASS_NAME   VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_TRIGGERS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    JOB_NAME  VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    NEXT_FIRE_TIME BIGINT(13) NULL,
    PREV_FIRE_TIME BIGINT(13) NULL,
    PRIORITY INTEGER NULL,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME BIGINT(13) NOT NULL,
    END_TIME BIGINT(13) NULL,
    CALENDAR_NAME VARCHAR(200) NULL,
    MISFIRE_INSTR SMALLINT(2) NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
        REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_SIMPLE_TRIGGERS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    REPEAT_COUNT BIGINT(7) NOT NULL,
    REPEAT_INTERVAL BIGINT(12) NOT NULL,
    TIMES_TRIGGERED BIGINT(10) NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_CRON_TRIGGERS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(200) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_SIMPROP_TRIGGERS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) NULL,
    STR_PROP_2 VARCHAR(512) NULL,
    STR_PROP_3 VARCHAR(512) NULL,
    INT_PROP_1 INT NULL,
    INT_PROP_2 INT NULL,
    LONG_PROP_1 BIGINT NULL,
    LONG_PROP_2 BIGINT NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 VARCHAR(1) NULL,
    BOOL_PROP_2 VARCHAR(1) NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
    REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_BLOB_TRIGGERS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_CALENDARS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    CALENDAR_NAME  VARCHAR(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_GROUP  VARCHAR(200) NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_FIRED_TRIGGERS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    ENTRY_ID VARCHAR(95) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT(13) NOT NULL,
    SCHED_TIME BIGINT(13) NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(200) NULL,
    JOB_GROUP VARCHAR(200) NULL,
    IS_NONCONCURRENT VARCHAR(1) NULL,
    REQUESTS_RECOVERY VARCHAR(1) NULL,
    PRIMARY KEY (SCHED_NAME,ENTRY_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_SCHEDULER_STATE
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
    CHECKIN_INTERVAL BIGINT(13) NOT NULL,
    PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE QRTZ_LOCKS
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME  VARCHAR(40) NOT NULL,
    PRIMARY KEY (SCHED_NAME,LOCK_NAME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


commit;
