package com.sample
 
import com.toolkit.drools.bean.Task;
import com.toolkit.drools.bean.Order;
 
// 注册获取5个积分

rule "CREDIT_REGISTER"
	no-loop  true
	lock-on-active true
	activation-group "addcredit by task"

    when
        $task : Task(taskType == 0 ) 
    then
		$task.setCredit(5);  	
end

// 完善资料获取2个积分

rule "CREDIT_COMPLETE_DATA"
	no-loop  true
	lock-on-active true
	activation-group "addcredit by task"

    when
        $task : Task(taskType == 1) 
    then
		$task.setCredit(2);  	
end

// 消费获取积分

rule "CREDIT_CONSUME"
	no-loop  true
	lock-on-active true
	activation-group "addcredit by order amount"

    when
        $order : Order( amount > 0,$amount:amount) 
    then
		$order.setCredit((int)$amount);	
end
 
 